= Deploy Jump App

== Deploy _Jump App_ Microservices

_Jump App_ is a microservice-based application created to emulate an enterprise application complex architecture with multi environments. This app allows users to configure a set of jumps between components and generate a continuous traffic flow defining the number of retries and their span of time.

First at all, it is required to deploy Jump App application in Openshift in order to have the demo application environment ready. The following steps in this section helps you to deploy _Jump App_.

WARNING: Please, replace *<user>*, *<pass>*, *<ocp_cluster_console>* and *<user_namespace>* with the values provided by the Instructor at the beginning of this tutorial or values obtained from openshift cluster.

[#login]
=== Login in Openshift

include::partial$oc_login.adoc[]

[#github]
=== Clone GitHub Repository

include::partial$clone_github_repo.adoc[]

[#jumpappobjects]
=== Create _Jump App_ Objects in Openshift

First at all, it is required to modify _params.env_ file to include the parameters provided by the Instructor:

[.lines_7]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd rh-service-mesh-v2-istio-crtlplane-resources
vi params.env
----

.params file content
====
USER_NAMESPACE=user1 +
OCP_APPS_DOMAIN=apps.tutorialrhmesh.sandbox507.opentlc.com
====

Once the params file is saved, you are able to process with _Jump App_ deployment phase:

[.lines_7]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project <user_namespace>
oc process -f 00-jump-app-template.yml --param-file=./params.env --ignore-unknown-parameters | oc create -f -
----

[.console-output]
[source,output,subs="+macros,+attributes"]
----
rolebinding.rbac.authorization.k8s.io/tekton-deployments-admin created
service/back-golang created
service/back-python created
service/back-springboot created
service/front-javascript created
deployment.apps/back-golang-v1 created
deployment.apps/back-python-v1 created
deployment.apps/back-springboot-v1 created
deployment.apps/front-javascript-v1 created
secret/mongo created
service/mongo created
deployment.apps/mongo created
route.route.openshift.io/back-golang-v1 created 
route.route.openshift.io/back-golang created 
route.route.openshift.io/back-javascript-v1 created
route.route.openshift.io/back-javascript created
----

[#test]
=== Confirm _Jump App_ is already running in Openshift

Once _Jump App_ objects have been created in Openshift, it is required to follow next steps in order to ensure your demo app is running properly:

include::partial$check_jumpapp.adoc[]

[#testapp]
=== Access to _Jump App_

Once _Jump App_ is already running in Openshift, it is time to access _Jump App_ public services in order to test the application:

include::partial$check_jumpapp_service.adoc[]