= Istio-Envoy Objects Relationship

== Review Red Hat Service Mesh objects

When a new Service Mesh object is created in a specific namespace, a set of configurations blocks are added to Envoy proxies in order to be able to apply these rules in the mesh traffic flow.

In this step, you will review how these objects affect Envoy proxies getting their configuration from Envoy itself.

WARNING: Please, replace *<user_namespace>* and *<pod_id>* with the values provided by the Instructor at the beginning of this tutorial or values obtained from openshift cluster.

[#dr]
=== Destination Rules

:name: Destination Rule
:object: destination-rule
:file_repo: 04-istio-envoy-relationship/00-istio-envoy-rel-drs.yaml

include::partial$relationship_step.adoc[]

[#vsvc]
=== Virtual Services

:name: Virtual Service
:object: virtual-service
:file_repo: 04-istio-envoy-relationship/01-istio-envoy-rel-vss.yaml

include::partial$relationship_step.adoc[]

NOTE: Additionally, perform a GET request using _curl_ in order to test out headers modification

[.console-input]
[source,input,subs="+macros,+attributes"]
----
curl -k -v https://back-golang-<user_namespace>.<openshift_apps_domain>/testing
----

[.console-output]
[source,output,subs="+macros,+attributes"]
----
...
< redirection: istio-envoy-relationship-test
...
{"code":200,"message":"/jump - Greetings from Golang!"}%  
----

Once the previous objects are applied, it is time to test our services again with a multiple number of connections. For this step, please follow the next steps:

:jumps: 1000
:seconds: 1

include::partial$check_jumpapp_mesh.adoc[]

[#se]
=== Service Entry

:name: Service Entry
:object: service-entry
:file_repo: 04-istio-envoy-relationship/02-istio-envoy-rel-ses.yaml

include::partial$relationship_step.adoc[]

[.console-input]
[source,input,subs="+macros,+attributes"]
----
oc rsh back-golang-v1-<pod_id>
curl -k -v https://www.google.es
----

[.console-output]
[source,output,subs="+macros,+attributes"]
----
...
  <body>
    <div>
      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>

      <div class="alert alert-info">
        <p class="info">
          Possible reasons you are seeing this page:
        </p>
        <ul>
          <li>
            <strong>The host doesn't exist.</strong>
            Make sure the hostname was typed correctly and that a route matching this hostname exists.
          </li>
          <li>
            <strong>The host exists, but doesn't have a matching path.</strong>
            Check if the URL path was typed correctly and that the route was created using the desired path.
          </li>
          <li>
            <strong>Route and path matches, but all pods are down.</strong>
            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>
----

IMPORTANT: Note that the response is generated by Openshift and not by _www.google.es_
