= Envoy Proxy

== Review Envoy Proxy through Envoy Filters


In Envoy Proxy, a _filter chain_ wraps a set of match criteria, an option TLS context, a set of filters, and various other parameters. When a request is received in an Envoy Proxy, a communication flow is generated going through a set of filter chains which might could modify this request in a number of ways.

As you reviewed in the previous section, when a new Service Mesh object is created in a specific namespace, a set of configurations blocks are added to Envoy proxies in order to be able to apply these rules in the mesh traffic flow.

In this step, you will review how _envoy filters_ affect Envoy traffic applying different rules based on a set of criteria.

NOTE: Please, replace *<user_namespace>* and *<pod_id>* with the values provided by the Instructor at the beginning of this tutorial or values obtained from openshift cluster.

[#ef]
=== Envoy Filters

:name: Envoy Filters
:object: envoy-filter
:file_repo: 05-envoy-proxy/00-envoy-proxy-ef.yaml

include::partial$relationship_step.adoc[]

NOTE: Additionally, perform a GET request using _curl_ in order to test out headers modification

[.console-input]
[source,input,subs="+macros,+attributes"]
----
curl -k -v https://back-golang-<user_namespace>.<openshift_apps_domain>/testing
----

[.console-output]
[source,output,subs="+macros,+attributes"]
----
...
< envoy-filter-test: rh-servicemesh-crtlplane-tutorial
...
{"code":200,"message":"/jump - Greetings from Golang!"}%  
----
