= Envoy Proxy

== Review Envoy Proxy through Envoy Filters


In Envoy Proxy, a _filter chain_ wraps a set of match criteria, an option TLS context, a set of filters, and various other parameters. When a request is received in an Envoy Proxy, a communication flow is generated going through a set of filter chains which might could modify this request in a number of ways.

As you reviewed in the previous section, when a new Service Mesh object is created in a specific namespace, a set of configurations blocks are added to Envoy proxies in order to be able to apply these rules in the mesh traffic flow.

In this step, you will review how _envoy filters_ affect Envoy traffic applying different rules based on a set of criteria.

NOTE: Please, replace *<user_namespace>* and *<pod_id>* with the values provided by the Instructor at the beginning of this tutorial or values obtained from openshift cluster.

[#ef]
=== Envoy Filters

:name: Envoy Filters
:object_file: envoyfilters-additional.yml
:object: envoy-filter

include::partial$relationship_step.adoc[]

[.console-input]
[source, java,subs="+macros,+attributes"]
----
oc rsh back-golang-v1-<pod_id>
$ curl -k -v https://www.google.es
----

[.console-output]
[source,output,subs="+macros,+attributes"]
----
...
  <body>
    <div>
      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>

      <div class="alert alert-info">
        <p class="info">
          Possible reasons you are seeing this page:
        </p>
        <ul>
          <li>
            <strong>The host doesn't exist.</strong>
            Make sure the hostname was typed correctly and that a route matching this hostname exists.
          </li>
          <li>
            <strong>The host exists, but doesn't have a matching path.</strong>
            Check if the URL path was typed correctly and that the route was created using the desired path.
          </li>
          <li>
            <strong>Route and path matches, but all pods are down.</strong>
            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>
----

IMPORTANT: Note that the response is generated by Openshift and not by _www.google.es_
