= Welcome to Red Hat Workshop - CI/CD & GitOps
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

_Red Hat Workshop CI/CD & GitOps_ is a repository which includes a tutorial with a set of practices for the purpose of practicing with Kubernetes Native CI/CD pipelines in a GitOps model.

The general idea behind this workshop is to get an initial understanding of the following points:

- Deploy microservice-based applications in Kubernetes using ArgoCD and Helm
- Operate applications in Kubernetes using ArgoCD in a GitOps model
- Implement Kubernetes Native CI/CD Pipelines strategy with Tekton

[.text-center.strong]
== Get Started

First of all, it is required to review your local machine prerequisites and laboratory environment access in order to be able to start working on this tutorial.

Please, follow xref:01-setup.adoc[Get Started] for more information.

[.text-center.strong]
== Tutorial Steps

=== Deployment Workflow

In this step, you will prepare a GitOps repository and deploy _Jump App_ application in Openshift using ArgoCD and Helm.

xref:02-deployment.adoc[Start this exercise...]

=== GitOps Workflow

In this step, you will xxxx

xref:03-gitops.adoc[Start this exercise...]

=== CI/CD Workflow

In this step, you will xxx

xref:04-cicd.adoc[Start this exercise...]