= Welcome to Red Hat Workshop - CI/CD & GitOps
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

_Red Hat Workshop CI/CD & GitOps_ is a repository which includes a tutorial with a set of practices for the purpose of practicing with Kubernetes Native CI/CD pipelines in a GitOps model.

The general idea behind this workshop is to get an initial understanding of the following points:

- Deploy microservice-based applications in Kubernetes using ArgoCD and Helm
- Operate applications in Kubernetes using ArgoCD in a GitOps model
- Implement Kubernetes Native CI/CD Pipelines strategy with Tekton

[.text-center.strong]
== Getting Started

First of all, it is required to review your local machine prerequisites and laboratory environment access in order to be able to start working on this tutorial.

Please, follow xref:01-setup.adoc[Getting Started] for more information.

[.text-center.strong]
== Tutorial Steps

=== Deployment Workflow

In this step, you will prepare a GitOps repository and deploy _Jump App_ application in Openshift using ArgoCD and Helm.

xref:02-deployment.adoc[Start this exercise...]

=== GitOps Workflow

In this step, you will make a change in your GitOps GitHub repository where application settings are located and then ArgoCD applies this configuration automatically.

xref:03-gitops.adoc[Start this exercise...]

=== CI/CD Workflow

In this step, you will perform a set of tasks in order to understand and implement a CI/CD strategy:

* Fork a _Jump App_ microservice project in order to be able to make changes in the source code
* Change some _Jump App_ microservices settings in a GitOps fashion
* Deploy a CI/CD project in Openshift
* Configure GitHub to notify your CI/CD project for changes
* Modify a microservice source code and integrate this new release in a continuous integration & deployment way

xref:04-cicd.adoc[Start this exercise...]