apiVersion: v1
kind: Template
metadata:
  name: jump-app-gitops-argocd-operator
objects:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ${USERNAME}-gitops-argocd
      namespace: ${USERNAME}-gitops-argocd
    spec:
      targetNamespaces:
      - ${USERNAME}-gitops-argocd
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: gitops-argocd
      namespace: ${USERNAME}-gitops-argocd 
    spec:
      channel: alpha
      name: argocd-operator
      source: community-operators
      sourceNamespace: openshift-marketplace 
parameters:
  - description: Username
    displayName: Username
    name: USERNAME
    required: true
  